version: '3.5'

# =========================================
# X-Templates
# =========================================
x-app-service: &app-service
  image: oanhnn/laravel:edge
  # build:
  #   context: .
  #   dockerfile: .docker/php/Dockerfile
  depends_on:
    - mysql
    - redis
  environment:
    REDIS_HOST:  redis
    DB_HOST:     mysql
    LOG_CHANNEL: stderr
  restart: unless-stopped
  volumes:
    - .:/var/www

# =========================================
# Networks
# =========================================
networks:
  mysql-net: {}
  redis-net: {}
  proxy-net: {}

# =========================================
# Volumes
# =========================================
volumes:
  mysql-vol: {}
  redis-vol: {}

# =========================================
# Services
# =========================================
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
      - --appendonly yes
      - --requirepass ${REDIS_PASSWORD:-password}
      - --bind 0.0.0.0
      - --port ${REDIS_PORT:-6379}
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-password}
    networks:
      - redis-net
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    restart: unless-stopped
    volumes:
      - redis-vol:/data
    healthcheck:
      test: redis-cli -h redis -p ${REDIS_PORT:-6379} ping
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 10

  mysql:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0
      - --port=$DB_PORT
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_USER:          ${DB_USERNAME:-dev}
      MYSQL_PASSWORD:      ${DB_PASSWORD:-devpass}
      MYSQL_DATABASE:      ${DB_DATABASE:-laravel}
    networks:
      - mysql-net
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    restart: unless-stopped
    volumes:
      - mysql-vol:/var/lib/mysql
      # - .docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: MYSQL_PWD=$$MYSQL_PASSWORD mysqladmin -h mysql -P ${DB_PORT:-3306} -u $$MYSQL_USER --silent ping
      start_period: 2s
      interval: 1s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - php
    networks:
      - proxy-net
    ports:
      - 80:80
      # - 443:443
    restart: unless-stopped
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - .docker/nginx/keys:/etc/nginx/ssl:ro
      - ./public:/var/www/public:ro

  php:
    <<: *app-service
    networks:
      - mysql-net
      - redis-net
      - proxy-net
    volumes:
      - .:/var/www
      - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  schedule:
    <<: *app-service
    command: artisan schedule:run --verbose --no-interaction --sleep=60
    networks:
      - mysql-net
      - redis-net

  horizon:
    <<: *app-service
    command: artisan queue:work
    networks:
      - mysql-net
      - redis-net
