networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
  sailminio:
    driver: local

services:
  redis:
    image: redis:alpine
    networks:
      - sail
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - sailredis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h $$HOSTNAME ping"]
      start_period: 15s
      interval: 3s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - sail
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - sailmysql:/var/lib/mysql
      # - docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=$$MYSQL_PASSWORD mysqladmin -h $$HOSTNAME ping"]
      start_period: 2s
      interval: 1s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:latest
    command: minio server /data/minio --console-address ":8900"
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    networks:
      - sail
    ports:
      - 9000:9000
      - 8900:8900
    volumes:
      - sailminio:/data/minio
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:9000/minio/health/live"]
      start_period: 2s
      interval: 1s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sail

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - laravel
    environment:
      PHP_FPM_ENDPOINT: laravel:9000
    networks:
      - sail
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/fpm.conf:/etc/nginx/templates/default.conf.template:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost/_health/nginx"]
      start_period: 2s
      interval: 1s
      timeout: 3s
      retries: 10

  laravel:
    image: registry.rabiloo.net/skrum/video-distribution-cms/php:runtime
    command: ["supervisord", "-c", "/etc/supervisord.conf"]
    depends_on:
      - mysql
      - redis
      - minio
      - mailhog
    env_file:
      - .env
    environment:
      REDIS_HOST:    redis
      DB_HOST:       mysql
      MAIL_HOST:     mailhog
      AWS_ENDPOINT:  minio:9000
      LOG_CHANNEL:   stderr
      LOG_LEVEL:     info
      LARAVEL_SAIL:  1
      XDEBUG_MODE:   develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - sail
    restart: unless-stopped
    volumes:
      - ./docker/php/www-data.cron:/etc/crontabs/www-data:ro
      - ./docker/php/supervisord.conf:/etc/supervisord.conf:ro
      - .:/var/www
