version: '3.5'

# =========================================
# X-Templates
# =========================================
x-app-service: &app-service
  build:
    context:    .
    dockerfile: .docker/php/Dockerfile
  depends_on:
    - mysql
    - redis
  environment:
    REDIS_HOST:  'redis'
    DB_HOST:     'mysql'
    LOG_CHANNEL: 'stderr'
  restart: unless-stopped
  volumes:
    - .:/var/www
    - .env:/var/www/.env

# =========================================
# Networks
# =========================================
networks:
  mysql-net: {}
  redis-net: {}
  proxy-net: {}

# =========================================
# Volumes
# =========================================
volumes:
  mysql-dt: {}
  redis-dt: {}

# =========================================
# Services
# =========================================
services:
  redis:
    image: redis:alpine
    networks:
      - redis-net
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-dt:/data

  mysql:
    image: mysql:8.0
    # PDO Doesn't support MySQL 8 caching_sha2_password Authentication
    # @see https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - mysql-net
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - mysql-dt:/var/lib/mysql
      # - .docker/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:stable-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/keys:/etc/nginx/ssl
    networks:
      - proxy-net

  php:
    <<: *app-service
    networks:
      - mysql-net
      - redis-net
      - proxy-net

  cron:
    <<: *app-service
    networks:
      - mysql-net
      - redis-net
