name: Test preset

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.composer
        key: cache-dependencies

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

  generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        options:
          - '--docker'
          - '--vuejs'
          - '--gitlab'
          - '--github'
          - '--tailwindcss'
          - '--eslint'
          - '--eslint --vuejs'
        laravel:
          - '^8.0'
        php:
          - 7.4
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setting up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: curl, dom, json, mbstring, openssl
        tools: phpcs, composer, phpunit
        coverage: none

    - name: Setting up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.composer
        key: cache-dependencies

    - name: Create project with composer
      run: composer create-project --prefer-dist laravel/laravel=${{ matrix.laravel }} ./ci-test --prefer-dist

    - name: Apply preset
      run: npx use-preset .. ${{ matrix.options }} --debug --no-interaction
      working-directory: ./ci-test

    - name: Install dependencies
      run: |
        npm install
        composer update
      working-directory: ./ci-test

    - name: Run lint
      if: contains(matrix.options, '--eslint')
      run: npm run lint
      working-directory: ./ci-test

    - name: Run coding style check
      if: contains(matrix.options, '--phpcs')
      run: phpcs --standard=phpcs.xml.dist
      working-directory: ./ci-test

    - name: Run with docker
      if: contains(matrix.options, '--docker')
      run: |
        docker-compose up -d
        sleep 20s
        curl http://127.0.0.1/
        docker-compose down
      working-directory: ./ci-test

    - name: Run build assets
      run: npm run production
      working-directory: ./ci-test

    - name: Run tests in the generated project
      run: php artisan test
      working-directory: ./ci-test
